# Generated by Django 4.1.2 on 2022-10-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Second_name', models.CharField(max_length=255)),
                ('Email', models.URLField()),
                ('Class', models.IntegerField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
